### ISSUE TITLE
Support multiple instances of pm2 running on single server

### ISSUE THREAD

**Issue by marshall007** [Unitech/keymetrics.io#16]
The best practice for managing processes under different users is outlined in [`Unitech/pm2 #734`](https://github.com/Unitech/PM2/pull/734#issuecomment-60133093). Using multiple users each with their own instance of pm2, if we call `pm2 interact` under each user only one process appears in the dashboard (presumably the last process metrics were received from).

**Comment by Unitech** [comment]
Set a different name when linking a PM2 to a server.

```
$ pm2 link <secret> <public> unique-server-name
```
