### ISSUE TITLE
Trying to mark issue as fixed error

### ISSUE THREAD

**Issue by RyanCopley** [Unitech/keymetrics.io#17]
RqlDriverError: Argument 1 to eq may not be `undefined`. at new RqlDriverError (/var/www/km-api/source/node_modules/rethinkdb/errors.js:14:13) at Eq.<anonymous> (/var/www/km-api/source/node_modules/rethinkdb/ast.js:1438:17) at Eq.RDBOp (/var/www/km-api/source/node_modules/rethinkdb/ast.js:1442:8) at new Eq (/var/www/km-api/source/node_modules/rethinkdb/ast.js:1837:37) at /var/www/km-api/source/node_modules/rethinkdb/ast.js:199:43 at Bracket.RDBVal.eq (/var/www/km-api/source/node_modules/rethinkdb/ast.js:201:7) at Object.Exception.retrieve [as delete] (/var/www/km-api/source/data_methods/exception.js:191:35) at exports.deleteExceptions (/var/www/km-api/source/controllers/bucket_data_controller.js:185:29) at callbacks (/var/www/km-api/source/node_modules/express/lib/router/index.js:164:37) at param (/var/www/km-api/source/node_modules/express/lib/router/index.js:138:11)

**Comment by jorge-d** [comment]
Should be fixed by now ? Feel free to reopen if you encounter another issue like this in the future.
