### ISSUE TITLE
Ability to authorize users who haven't registered

### ISSUE THREAD

**Issue by marshall007** [Unitech/keymetrics.io#20]
Under `Settings > Users authorized` if you attempt to add users who aren't already registered you get a *"User unknown"* error. It would be nice if users received an invitation email to register on Keymetrics and join the bucket.

**Comment by lupino3** [comment]
+1, would be useful.

**Comment by lklepner** [comment]
+1

**Comment by IkKan** [comment]
1+

**Comment by jorge-d** [comment]
Done !
