### ISSUE TITLE
Not able to use cpu profiling and memory snapshot

### ISSUE THREAD

**Issue by hemantforever007** [Unitech/keymetrics.io#211]
When i visit cpu profiling page.

This is the message..
"To use profiling, you need: @pm2/agent >=0.0.1 (current: undefined)."

When i visit memory snapshot page.

This is the message..
"To use profiling, you need: nodejs apm >=2.1.0 (current: 1.6.4). @pm2/agent >=0.5.9 (current: undefined)."
Please help with this.

Pm2 version is 2.10.1

**Comment by vmarchaud** [comment]
You need to upgrade to the latest pm2 version, which will fix the issue.
