### ISSUE TITLE
Alert is not being triggered

### ISSUE THREAD

**Issue by adibenmat** [Unitech/keymetrics.io#213]
Hello
Im running the following script:

const io = require('@pm2/io');
const cpuUsage = require('cpu-percentage');
const cron = require("node-cron");
let syncInterval = 10;

io.init({
  metrics: {
    network: {
      ports: true
    }
  }
})

console.log(cpuUsage());

cron.schedule(`*/${syncInterval} * * * * *`, async function(){
  const cpuMetric = io.metric({
    name: 'CPU usage',
    value: () => {
      return cpuUsage().percent;
    },  
    alert: {
      mode: 'threshold',
      value: 5,
      msg: 'Detected over 5% CPU usage', // optional
      action: () => { //optional
        console.error('Detected over 5% CPU usage');
      },
      cmp: (value, threshold) => { //optional
        return (parseFloat(value) > threshold); // default check
      }
    }
  });
});

with node on a pm2 process, I'm not getting any emails or slack messages.

What am I doing wrong?

Thanks,
Adi,

**Comment by vmarchaud** [comment]
Alert have been removed from `@pm2/io`, they are now completely server side and only available in https://pm2.io/enterprise

**Comment by adibenmat** [comment]
How can I create a custom notification then? I'm using pm2 enterprise, but the documentation lead me to old  documentation page...

Thanks,
 Adi.
