### ISSUE TITLE
Unable to retrieve Logs from Dashboard

### ISSUE THREAD

**Issue by zigzactly** [Unitech/keymetrics.io#215]
Hi there. Viewing logs in the dashboard times out for me and returns me the following error:
`An internal error occured. Please retry later or contact the support.`

I have added a custom NodeJS server. Everything else seem to be working fine. 

Looking at the local logs on the server in ~/.pm2/agent.log there is a line which says:
`interactor:interface Transporters are not connected, connect them with: 
{"push":"https://theta.keymetrics.io:80","ws":"wss://theta.keymetrics.io/interaction/public","reverse":"https://theta.keymetrics.io:43554","realtime":"https://theta.keymetrics.io:443","web":"https://theta.keymetrics.io:443"}`

Could this be related? Please advise on what to do, thanks.

**Comment by Eywek** [comment]
Hi, did you have any custom actions that you can try ?
