### ISSUE TITLE
defaultInterpreter is not defined

### ISSUE THREAD

**Issue by mjafartp** [Unitech/keymetrics.io#217]
when i traying to start using code 
`pm2 start bin/www --name "api-app"`

getting an error 
defaultInterpreter is not defined
⇆  PM2+ activated | Web: https://app.pm2.io/#/r/3exxxxxxxxxxxx | Server: <SERVER NAME> | Conn: Websocket

also server not starting...

**Comment by vmarchaud** [comment]
See https://github.com/Unitech/pm2/issues/4106
