### ISSUE TITLE
mark probe not working as I understand it

### ISSUE THREAD

**Issue by RyanCopley** [Unitech/keymetrics.io#22]
```
var hourlyRequests = axm.probe();

var meter = hourlyRequests.meter({
  name    : 'req/hr',
  seconds : 3600
});

app.use(function (req, res, next) {
    meter.mark();
});
```

When I implement that, then do 
```
ab -n 10000 -c 100 https://mysite
```

My probe shows:
req/hr
0.68

I have no idea what this would possibly mean. I followed the example posted on the website and I would expect it to say 10000, not 0.68

**Comment by jorge-d** [comment]
Hi @RyanCopley,

Could you try with the latest version of [PMX](https://github.com/keymetrics/pmx), which should be fully compatible with **axm** and tell us whether you still have a problem with this probe or not?

Thanks,

**Comment by alavit-d** [comment]
HI @RyanCopley,

We reviewed the code and the **seconds** option was actually indicating over which interval you wanted to analyze your value, and not the refresh rate itself.
For you it meant you had approx **0.68 req/sec** over a one-hour interval.

We changed the options for clarity, please refer to the [PMX README].(https://github.com/keymetrics/pmx/)

Thanks
