### ISSUE TITLE
Unable to transfer project ownership

### ISSUE THREAD

**Issue by eridal** [Unitech/keymetrics.io#221]
Hi all,

We are trying to transfer a live project from my developer account into the company's owner, which has billing enabled and the endpoint is returning 404.

This message is written on the console:

```
Notification: Cannot POST /api/bucket/5d0c1763ef9ce356bb8c0a32/transfer_ownership
```

**Comment by Eywek** [comment]
Hello,

It should be fixed sorry

**Comment by eridal** [comment]
Hi @Eywek Thanks for the quick reply.

Now the endpoint is replying: 

```json
{"msg":"Missing parameters","fields":["newowner"]}
```

The issue is that the UI is sending the parameter as `new_owner`

**Comment by Eywek** [comment]
Hello,
Right, it should be fixed now.

**Comment by eridal** [comment]
Thanks @Eywek 

We managed to transfer the project by inspecting the request and manually sending the request with the fixed parameter, but anyway thanks for fixing this!
