### ISSUE TITLE
Bucket Disabled Error

### ISSUE THREAD

**Issue by vabajaa** [Unitech/keymetrics.io#223]
On my server, I'm currently unable to run pm2 for more than a few days without encountering an error that causes pm2 to restart entirely wiping all data and not restarting any of my node files.

I've attempted to contact pm2 and key metrics twice by email with no response and I am now turning to here for help

(I really don't want to have to look for a replacement but I'm running out of ideas.)

![image](https://user-images.githubusercontent.com/32213681/62754109-538ecd00-ba23-11e9-8f45-f78ce722f3b9.png)

**Comment by Eywek** [comment]
What's your bucket public id?

**Comment by vabajaa** [comment]
c138m2m71boc57m

**Comment by Eywek** [comment]
It should be fixed but you were in the old pricing free plan, with any feature enabled.

**Comment by sarveshkapil** [comment]
On my server, I'm currently unable to run pm2 for more than a few days without encountering an error that causes pm2 to restart entirely wiping all data and not restarting any of my node files.

I've attempted to contact pm2 and key metrics twice by email with no response and I am now turning to here for help

**Comment by sarveshkapil** [comment]
how i solve this
please suggest

**Comment by Eywek** [comment]
I’m not working here anymore sorry

**Comment by sarveshkapil** [comment]
please suggest what i do now?
how i solve this
