### ISSUE TITLE
Cannot read property 'offer_type' of undefined

### ISSUE THREAD

**Issue by mvillaizan** [Unitech/keymetrics.io#225]
As of today PM2 plus won't work/connect, whenever initializing the module (pm2 plus) I get:

`
[PM2 I/O] Successfully authenticated
[PM2 I/O] Successfully validated
(node:5464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'offer_type' of undefined
    at C:\Users\m\AppData\Roaming\npm\node_modules\pm2\lib\API\pm2-plus\PM2IO.js:306:49
    at Array.forEach (<anonymous>)
    at io.bucket.retrieveAll.then.res (C:\Users\m\AppData\Roaming\npm\node_modules\pm2\lib\API\pm2-plus\PM2IO.js:305
:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by krlozadan** [comment]
I am having the same issue just trying to login using: `pm2 plus`
```
[-] Logging to pm2.io
[+] Logged in!
[PM2 I/O] Error: TypeError: Cannot read property 'offer_type' of undefined
```
Using

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

I don't know if it is related... but when I log in to the PM2 dashboard I cannot access my buckets

**Comment by mvillaizan** [comment]
It's a complete mess and they don't offer support, I recommend you move on, start using some orchestration tool and containers, this is dead.

**Comment by Unitech** [comment]
Fixed since PM2 4.x release.
Please update:
```
npm install pm2@latest -g
pm2 update
```
