### ISSUE TITLE
My server keeps getting locked, unable to get it to unlock

### ISSUE THREAD

**Issue by RyanCopley** [Unitech/keymetrics.io#23]
http://i.imgur.com/MZGx8jW.png

I'm not sure what is happening here, but I can even nuke the repo on the server and re-clone it and it never unlocks. I have to do a pm2 interact delete and re-create it to get it to unlock.

**Comment by tianp** [comment]
Just happened in my server also, when I tried to pull and the server locked it never unlocks. Trying to do pm2 interact delete and re-create it like @RyanCopley did, but it still locked.

**Comment by jorge-d** [comment]
Thank you for reporting this, @jshkurti Any thoughts on this?

**Comment by jshkurti** [comment]
I'm working on it.

**Comment by Unitech** [comment]
@RyanCopley can you show us your process.json or how you started your app?

**Comment by hertzg** [comment]
Same issue. When I'm trying to pull but there are no changes on the repository it gets locked and never unlocks unless you run `pm2 delete app_id_here` and `pm2 start processes.json`

**Comment by jshkurti** [comment]
Is your versioning tool git ?
If you perform a ```git remote update``` on your app directory, does it require a password ?

**Comment by hertzg** [comment]
@jshkurti I'm using ssh key authentication and I've just checked and it does not require password or anything, just returns `Fetching origin`
