### ISSUE TITLE
Plus account appears free account

### ISSUE THREAD

**Issue by semihozkoroglu** [Unitech/keymetrics.io#234]
Hi, I upgraded my account to plus account two day ago, yesterday my account showed as free account. I wrote an mail but there is no any answer. This is a bug? Why did I encounter a mistake? Can you help me. Thank you.

<img width="1320" alt="Screen Shot 2020-01-22 at 16 44 10" src="https://user-images.githubusercontent.com/265930/72972515-a2b39900-3ddc-11ea-9951-b2339496e85e.png">

**Comment by Unitech** [comment]
fixed
