### ISSUE TITLE
Memory usage is not correct value

### ISSUE THREAD

**Issue by ariskemper** [Unitech/keymetrics.io#24]
In dashboard there is memory usage for each host runing PM2 and it doesn't show correct value. In our system usage is 400MB from 2GB and keymetrics dashboard is showing 1.8GB/2GB.

**Comment by viion** [comment]
I too am seeing this, its showing red: **962.5 MB / 988.9 MB**

**htop**
```  348/988MB ```

**free-m**
```             
             total       used       free     shared    buffers     cached
Mem:           988        978         10         19         77        549
-/+            351        637
Swap:          255          7        248
Total:        1244        985        258
```

**Comment by matteocontrini** [comment]
Keymetrics takes the wrong value.
As explained [here](http://www.linuxatemyram.com/) at the end of the page, the value that should be considered is the one that accounts buffers and cache. There are [plenties](http://gog.is/linux+right+free+memory) of topics on StackExchange and other sites [talking](http://stackoverflow.com/a/17618820/1633924) about this.

**Comment by tianp** [comment]
Hi there, I'm experienced same issue. In the dashboard it shows ```837.2 MB / 989.3 MB``` and in htop shows ```310/989 MB```

**Comment by jorge-d** [comment]
Hi !

We are aware of this issue however it comes from the fact that there is no way to do an out-of-the-box checking of the real available value in NodeJS, and by this I mean a "native" way. See the [os documentation](http://nodejs.org/api/os.html).

We will soon provide a way to get those data easily extracted on every single platform and displayable on our monitoring dashboard in a few weeks, I'll have to ask for your patience on that :)

**Comment by tianp** [comment]
Hi @jorge-d thanks for your response.

I'm notice that memory usage is still displayed in the dashboard, so what are you saying that we have to ignore that memory usage display until it fixed?

**Comment by jshkurti** [comment]
Exactly :)

**Comment by tianp** [comment]
In think you need to put little info/notice on displayed memory usage that it might be incorrect, until it fixed.

**Comment by jorge-d** [comment]
@tianp Well technically this memory usage is not incorrect :)

But I agree that this is misleading. We'll see what we do about it temporarily until we fix the issue for good.
Cheers,

**Comment by Unitech** [comment]
the data display on top of process list will be removed in the future.
A module system in pm2 will able to install a specific application dedicated to monitor your server with multiple custom metrics for measuring I/O, Disk usage, CPU/Memory (+ maybe other things like security updates) in realtime + 14 days value retention

**Comment by samuelgbrown** [comment]
+1 for fixing and giving users transparency, just gave you guys a go and although I like the interface, this is kinda a dealbreaker (and scary). In contrast, NewRelic shows me what I really want to see (1.2gb/7.5gb, not 7gb/7.5gb). Good luck!

**Comment by jorge-d** [comment]
Hey,

As @Unitech stated we have chosen to drop this piece of the dashboard until we release the new module that will allow you to monitor I/O, Disk Usage, Cpu etc...

Keep in touch for the future releases :)

**Comment by Mishit07** [comment]
I can't see the total physical memory vs occupied.
