### ISSUE TITLE
Awkward UI

### ISSUE THREAD

**Issue by RyanCopley** [Unitech/keymetrics.io#27]
https://i.imgur.com/80B8dSX.png

That "Activate / Deactivate" button isn't very clear and i'm not sure wether it's activated or deactivated, it's very confusing from a customer POV

**Comment by Unitech** [comment]
Gotcha thanks for the feedback, I found the bug and fixed it, will be push very soon

**Comment by RyanCopley** [comment]
So the buttons weren't working? Cause I'm receiving hundreds of emails a day and want to stop it :/

**Comment by Unitech** [comment]
Whats your bucket name so I can switch it to another Keymetrics server?
