### ISSUE TITLE
Re : Cannot access Bucket 

### ISSUE THREAD

**Issue by pgamerx** [Unitech/keymetrics.io#272]
So I tried opening the bucket 
And I have 4 processes in the bucket 
I need to restart one really badly but I can't login 
Pls help 
It says unexpected error try again later

**Comment by ShakirovMars** [comment]
I have the same problem

**Comment by christopheSeeka** [comment]
Same.

**Comment by sphaxa** [comment]
I have a massive deployment today, if I cannot access my buckets this is going to be a huge blow.

**Comment by pgamerx** [comment]
Feel baad for you guys 
There is one thing you guys can do 
I made it work by deleting pm2 process 
Using pm2 delete 
Then pm2 start 
So it kinda restarted it but I know it's not permanent solution 
Also to know errors etc I use pm2-discord 
It uses discord webhook to directly tell logs 
You don't need to login to pm2 to use it just need to access pm2 using terminal 
Here is how 
https://github.com/FranciscoG/pm2-discord

**Comment by pgamerx** [comment]
Issue has been fixed by Pm2 itself
