### ISSUE TITLE
bad uptime

### ISSUE THREAD

**Issue by PierrickP** [Unitech/keymetrics.io#30]
![image](https://cloud.githubusercontent.com/assets/1214544/5877159/f5404524-a31d-11e4-8674-aa32359ccd7b.png)

I don't know what is keymetrics uptime but it's not my server uptime.

**Comment by Unitech** [comment]
Thanks for reporting this bug

@Atelier-Morales @Kyoshim 
https://github.com/keymetrics/km-front/blob/master/app/js/filters/misc.filter.js#L57

**Comment by Atelier-Morales** [comment]
Hi Pierrick, 
We just fixed this bug, could you please check and confirm that you're getting the correct uptime?

Thanks again, 

Fernan

**Comment by PierrickP** [comment]
Purrfect ! :cat:
