### ISSUE TITLE
app.pm2.io browser dashboard CORS issue

### ISSUE THREAD

**Issue by warocked** [Unitech/keymetrics.io#303]
**Error:**
`Access to XMLHttpRequest at 'https://freenode-3.keymetrics.io/api/bucket/<Bucket ID>/users_authorized' from origin 'https://app.pm2.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Reproduce**
1. Login to app.pm2.io dashboard
2. Select any bucket
3. Check browser console logs

**Comment by galipmedia** [comment]
Having the same problem today.
