### ISSUE TITLE
No application has been launched keeps flashing if two pm2 instances interact

### ISSUE THREAD

**Issue by tuhoojabotti** [Unitech/keymetrics.io#31]
I accidentally started pm2 interact with wrong user first and then with the correct user and it caused the dashboard to flicker sometimes showing my processes and sometimes showing nothing. I guess it is because it was getting data about empty pm2 list and the one with all processes all the time.

Would be nice to detect this somehow, because it makes it seem like the dashboard is buggy.

**Comment by Unitech** [comment]
Hey,

Yes you must not have two interactors sending data to keymetrics from the same hosts.
Kill the useless one by hand (PM2: Keymetrics.io Agent) or do a `pm2 interact kill` with the first user you started the interactor with.

**Comment by Unitech** [comment]
It will be fixed once you give the right name to your agent via 

```
$ pm2 interact secret_key public_key [MY_MACHINE_NAME]
```

Best,
Alex
