### ISSUE TITLE
Unable to add new server to bucket

### ISSUE THREAD

**Issue by WTF-Software** [Unitech/keymetrics.io#314]
I'm unable to add a new server to a bucket.

I follow the simple instructions on PM2.io but it doesn't appear in the list (install, link, start).

When I run 'pm2 plus', after running 'pm2 link', it authenticates ok, but then tells me to run 'pm2 plus' again and does not appear in  my bucket.

I'm using the free monitor (4) with only 2 servers in the bucket.

pm2 version: 5.2.0
NodeJs version: v12.22.9

Help?

**Comment by multikitty** [comment]
Please try to execute "pm2 monitor".

**Comment by WTF-Software** [comment]
> Please try to execute "pm2 monitor".

Thanks for the suggestion but I get the same result - prompted to execute 'pm2 plus'

**Comment by Nadejde** [comment]
Did you manage to solve this issue by any chance? I'm having the same problem right now and I'm not sure how to progress. More details:
* I am on the free plan trying to test it out
* I already have pm2 running with several processes and all is working as expected
* EDIT: perhaps one key thing to mention is that I'm running python processes with PM2
* I have done `pm2 monitor` and added one of the apps and it has a green dot next to its name 
* When I run `pm2 open` I get this message:  `Agent if offline, type `$ pm2 plus` to log in`
* When I run `pm2 plus` this is the result:
`pm2 plus

[PM2 I/O] Successfully authenticated

[PM2 I/O] Successfully validated

[PM2 I/O] If you don't want to connect to a bucket, type 'none'

[PM2 I/O] Type the name of the bucket you want to connect to : ***

[PM2 I/O] Using: Public key: *** | Private key: *** | Machine name: ***

[PM2 I/O] Run `$ pm2 plus` to connect
`

I'm not sure how to move forward with this:(

**Comment by WTF-Software** [comment]
Sadly, I haven't been able to fix the issue.

It is still occurring for me.

**Comment by conidig** [comment]
Everyone still having the issue? Same here.

**Comment by codykociemba** [comment]
Same issue, any fixes?

**Comment by sanalSynigence** [comment]
I am having the same issue, any one have any solution?

**Comment by WTF-Software** [comment]
I managed to fix the issue.

I checked the agent.log in ~/.pm2/logs and saw that an error was occurring due to the optional chaining operator (.?).

Support for this only became available in Node 14.4+. I was running v12.22.x.

Upgraded Node - all fixed.
