### ISSUE TITLE
Dashboard 'online for' tile does not update

### ISSUE THREAD

**Issue by bazineta** [Unitech/keymetrics.io#34]
![km](https://cloud.githubusercontent.com/assets/564060/5989591/0f296eb4-a942-11e4-9162-030e9cd55428.png)

This pictured portion of the dashboard tile does not appear to auto-update.  Bit disconcerting at first.

Otherwise, wow, great execution, very impressed.

**Comment by Unitech** [comment]
Thanks for your feedback!

Just fixed it, as we use AngularJS 1.3.x we made some optimization with the bind-once feature to make the dashboard faster.

Hope you like the dashboard and feel free to drop us an email about what you love and dont!
