### ISSUE TITLE
Server is reported online - but no apps are showing

### ISSUE THREAD

**Issue by LarsBuur** [Unitech/keymetrics.io#35]
When I run pm2 monit then my app are displayed and the tasks are executed fine. 

The server is displayed in https://app.keymetrics.io/ 

I just updated pm2 using npm install git://github.com/Unitech/pm2#master -g
The server console reports: PM2 version: 0.12.4  

The only thing that I am doing differently from the demo project is using a json file for my startup parameters. 

This is the json config file:

```
{
  "name": "XXX-worker",
  "script": "/usr/local/bin/XXXX-worker/XXXXrunner.js",
  "log_date_format": "YYYY-MM-DD HH:mm Z",
  "watch": true,
  "env": {
    "NODE_ENV": "production",
    "MONGO_URL":"mongodb://mongoURLXXX",
    "HOST":"XXX",
    "PORT":"80",
    "XXXX_API_HOST":"api.cint.com"
  }
}
```

This is how the runner is started:
```
pm2 start XXX-process.json
pm2 startup ubuntu
pm2 save
```

Any tips?

Best regards,
Lars

**Comment by LarsBuur** [comment]
I should note that I just cloned the playground project using:

```
git clone https://github.com/keymetrics/app-playground.git
cd app-playground
pm2 start app.js --watch
```

and the new app is also running now and showing up in pm2 monit but not in app.keymetrics.io

**Comment by Unitech** [comment]
Hello!

We fixed the data transfer between PM2 and Keymetrics.
Could you try with this version of PM2:

```bash
$ npm install git://github.com/Unitech/pm2#development -g
$ pm2 interact XXX XXXX
```

Thanks

**Comment by LarsBuur** [comment]
Thank you very much. I updated PM2 and now the data are available in app.keymetrics.io. 

Great!
