### ISSUE TITLE
Scrollbars needed in most windows

### ISSUE THREAD

**Issue by LarsBuur** [Unitech/keymetrics.io#36]
I just spawned four workers using PM2 and keymetrics. It seems silly that I need to select each server to see the server metrics. I would much prefer just being able to scroll between the servers but the vertical scrollbar is disabled.

Another thing. I pressed the "Delete server and all info" button for all my servers afterwards - but for some reason the app selector in the top are still displaying the previous app´s - which should be deleted.

**Comment by Unitech** [comment]
Hey Lars,

Thanks for reporting this.
We tried with Windows and Chrome and there is a scroll bar at the right of the page. Could you make any screenshot to help us debug this?

When you clicked on the button "Delete Server and associated data" did you unlinked your PM2s from Keymetrics?

Cheers!

**Comment by LarsBuur** [comment]
I am using a MacBook pro and Google chrome (Version 40.0.2214.94 (64-bit)) 
The vertical scrollbars are showing now so this is not an issue anymore. 

Regarding the "Delete Server and associated data". I started by deleting the server nodes (hard shutdown) and then clicked the "Delete Server and associated data". What pusssled me was the fact that the demo app was still present in the "Filter by app name" in the topnav - but it has disappeared now.

All is good. 

Lars
