### ISSUE TITLE
AngularJs Problem in the interface

### ISSUE THREAD

**Issue by AlexandreAWE** [Unitech/keymetrics.io#37]
Hi there is a problem in the interface
![capture d ecran 2015-02-05 a 10 56 09](https://cloud.githubusercontent.com/assets/7659157/6058228/af2fe668-ad25-11e4-85b2-ac4bedeab058.png)

**Comment by jorge-d** [comment]
Hi @AlexandreAWE ! Thanks for reporting this,
We had a small outage a few hours ago, do you still get this error?

**Comment by AlexandreAWE** [comment]
@jorge-d nop it works thanks ! :)

**Comment by Unitech** [comment]
We are still working on our infrastructure so some times it may hangs, but it's getting better day to day. *Do more faster*

Cheers!
