### ISSUE TITLE
Weird font

### ISSUE THREAD

**Issue by dandv** [Unitech/keymetrics.io#4]
Congrats on the launch! :+1: 

The font looks wavy on my Chrome on Windows. `v` and `w` are taller than the other letters. `y` is bigger too.

![image](https://cloud.githubusercontent.com/assets/33569/5060204/8f44f0f2-6cfa-11e4-985d-78bf994c8160.png)

The word "statistics" looks strange too. I've never filed an issue against fonts on a website, but this one looked strange :)

**Comment by jorge-d** [comment]
This issue has been staling for too long :p I'm closing this now since the landing has changed since then.

Anyway thank you for reporting this.
