### ISSUE TITLE
Log tailing

### ISSUE THREAD

**Issue by btmdave** [Unitech/keymetrics.io#40]
Is there a way to tail error/out logs? If not, is this a feature that could be added?

**Comment by Unitech** [comment]
From Keymetrics or with PM2 ?

With pm2 you can do `pm2 logs`

**Comment by btmdave** [comment]
I was thinking from within Keymetrics...

**Comment by Unitech** [comment]
Yes would be an interesting feature for sure. We still have to think about it, maybe in the next month we will do it, if everyone ask for :)

**Comment by btmdave** [comment]
Very cool.  Maybe as an option however, to avoid the transfer overhead when it's not wanted.

**Comment by Unitech** [comment]
The secret sauce is upcoming in the next month! :D

**Comment by btmdave** [comment]
Always enjoy secret sauce :)

**Comment by marshall007** [comment]
Any update on this? I would also really benefit from having this feature.

**Comment by Unitech** [comment]
We are working on a plugin sections in Keymetrics, so you will be able to enable the features you need. It will be ready released in one and half month I think

**Comment by sean-hill** [comment]
:+1: For this! :)

**Comment by schaitanya** [comment]
+1

**Comment by ChrisAlvares** [comment]
+1!

**Comment by sunwenchao** [comment]
+1

**Comment by mastermind202** [comment]
It would be a fantastic feature.  I actually expected some sort of logging and it was one of my main reasons for signing up to Keymetrics.  It's a great product, but logging with make it exceptional.

**Comment by buunguyen** [comment]
:+1: especially useful for multi-server deployment. Really don't want to `pm2 logs` in each server.

**Comment by remkoboschker** [comment]
+1

**Comment by greenlikeorange** [comment]
+1

**Comment by Fredev** [comment]
+1

**Comment by Cu3PO42** [comment]
+1

**Comment by YaManicKill** [comment]
So, you claimed to have this nearly done at the end of February. Any news? This would be very useful.

+1

**Comment by jorge-d** [comment]
Patience you must have. Available soon, it will be.

**Comment by buunguyen** [comment]
Any update? In Keymetrics dashboard, I see the option to view logs but it asks to upgrade. I can upgrade but I need to know for sure this it is the same as the feature being discussed on this thread.

**Comment by Unitech** [comment]
The feature on keymetrics display logs in real time

**Comment by snowcxt** [comment]
I can't find the logs in the Keymetrics dashboard.

**Comment by assafbahat** [comment]
+1, Any updates on that?

**Comment by axs221** [comment]
+1, same as others, we would love to not have to ssh into our cloud servers to see the log history
