### ISSUE TITLE
big fat proxy

### ISSUE THREAD

**Issue by rafepurnell** [Unitech/keymetrics.io#41]
Just started using PM2.. 

Thank you so much for what you have created. So far I love it. Finally get the performance out of my application that I wanted.

Would love to use keymetrics but am stuck behind a corporate firewall/proxy 

Can you give me any advice?

Regards

Rafe Purnell

**Comment by Unitech** [comment]
Hello Rafe!

Thanks for these kind words!

We are working on a way to proxify cleanly the data sent from PM2.
Currently we already have a new version of the protocol that sends data though the port 80 by TCP.

You can try it by installing this PM2 version:

```bash
$ npm install git://github.com/Unitech/pm2#development -g
```

Tell me if it's working,
Best!

**Comment by jorge-d** [comment]
@rafepurnell Any news?

**Comment by Unitech** [comment]
We are going to work on a full websocket transmission between pm2 and keymetrics

**Comment by pichi12** [comment]
Hello there,

We are using pm2 v 1.0.2 , we are also having problems using keymetrics. We could not connect to them inside of our corporate LAN (It works with a public IP).

We have a kerio firewall, and we have been testing lots of configurations without success. We can see some handshakes between our server and the keymetric server IPs, but that is all.

It has been any progress in this subject?

Thank you very much.
