### ISSUE TITLE
CPU usage keeps rising

### ISSUE THREAD

**Issue by HalfdanJ** [Unitech/keymetrics.io#43]
My CPU monitor keeps rising to far far above 100%. My servers are running Windows Server 2012, and pm2  version 0.12.6
![skaermbillede 2015-02-25 kl 12 14 43](https://cloud.githubusercontent.com/assets/227529/6369597/38c9ef46-bce8-11e4-9dd9-bc9faebecef5.png)

**Comment by jorge-d** [comment]
Hi @HalfdanJ, could you run the `pm2 monit` command and tell use whether the values displayed have issues as well? Thanks,

**Comment by HalfdanJ** [comment]
I'm not really sure. One of the applications is showing 100% cpu usage, (but the system only uses 13% currently), the other one is low. 

![skaermbillede 2015-03-10 kl 12 26 12](https://cloud.githubusercontent.com/assets/227529/6574029/beb56418-c720-11e4-89f0-9b0fd2387ca6.png)

**Comment by HalfdanJ** [comment]
The second app just jumped to 100%, i think the terminal might have had a freeze. So it seems like its a pm2 issue on windows. 

![skaermbillede 2015-03-10 kl 12 33 02](https://cloud.githubusercontent.com/assets/227529/6574123/a5f3b528-c721-11e4-9c2b-8681e189460e.png)

**Comment by jorge-d** [comment]
It's what I was thinking of :) I open a new issue on pm2! Thank you for reporting this

**Comment by jorge-d** [comment]
Closing here, feel free to comment in the Pm2 issue directly :)
