### ISSUE TITLE
design of dashboard display

### ISSUE THREAD

**Issue by rbarkas** [Unitech/keymetrics.io#47]
It would be good if there was some way to adjust the character sizing / column widths of the dashboard display.  For my system, I can't see the process names (they truncate because the font size is too big) and the CPU and MEM columns display very big, taking up unecessary screen space.

Maybe also add the ability to collapse / enlarge the sidebar on the left side of screen.

Other than that, nice work people!

**Comment by rbarkas** [comment]
Another example of how configuration by user could save screen real estate would be by allowing user to disable / enable display of the the column that allows Rollback / pull / upgrade, also the column that shows http avg time (which isn't relevant to tasks that don't do http responses).

**Comment by jorge-d** [comment]
Thank you for your feedback, we'll improve the dashboard experience as time goes, stay tuned :)

**Comment by jorge-d** [comment]
You can now expand horizontally a server on the dashboard using the following icon on the left:
![screen shot 2015-03-25 at 18 56 57](https://cloud.githubusercontent.com/assets/1178099/6831465/bfaa3950-d320-11e4-8d60-6e5834640767.png)

We'll work on improving the UI/UX during the next weeks, I'm closing this issue in the meantime, feel free to reopen it.

**Comment by rbarkas** [comment]
Thanks Dimitri.  Your change solves mt problem and looks good.

Roy
