### ISSUE TITLE
A post from reddit to think about.

### ISSUE THREAD

**Issue by RyanCopley** [Unitech/keymetrics.io#49]
https://www.reddit.com/r/node/comments/2ygl50/how_should_i_be_using_pm2_in_production/

They bring up good points. Perhaps develop a modular system where a "redis" administration area could be, or at least some integration...

Maybe that would be feature creep, but I'd like to at least start a conversation.

Congrats on going public :+1:

**Comment by jorge-d** [comment]
Thank you for linking this @RyanCopley, as @Unitech (tknew) stated in the reddit link we are preparing some awesome features for pm2/Keymetrics :)

We'll think about a redis administration system !
