### ISSUE TITLE
UI Defect - Online For n Hours In Dashboard Is Incorrect.

### ISSUE THREAD

**Issue by gunish** [Unitech/keymetrics.io#50]
Offline App's show as online for --- hour. Example in screenshot below.

![screen shot 2015-03-10 at 12 23 04](https://cloud.githubusercontent.com/assets/1183862/6574796/46c50c7e-c720-11e4-84d7-10522274b4cb.png)

**Comment by jorge-d** [comment]
Should be fixed now :)
