### ISSUE TITLE
Congrats screen always showing up

### ISSUE THREAD

**Issue by jfbelisle** [Unitech/keymetrics.io#51]
Hi,

I've start interact on one of my pm2 instance and I can confirme that the agent is online when I "pm2 list"

I've tailed my agent.log file and the last line is showing 
[REV] Connected to http://cl3.keymetrics.io:43554

I assume everything should be setup ok but the congrats screen is always showing and even if I hide it using the chrome dev tools to see underneat it the dashboard is empty, I can only browse to me settings and alerts panel.

Thank you

JF

**Comment by jshkurti** [comment]
There are 3 possible reasons for this to happen :
1. You don't have a recent pm2 version.
2. You are behind a company proxy or something alike.
3. You didn't refresh your Keymetrics page.

**Comment by jfbelisle** [comment]
I'm running 0.12.3, is it recent enought ?

**Comment by jshkurti** [comment]
I would highly suggest you to use the latest version which is 0.12.7 and please let us know if it works.

**Comment by jfbelisle** [comment]
Awesome !! It works like a charm with 0.12.7.

Great job by the way !
