### ISSUE TITLE
pm2 list doesn't work after pm2 interact

### ISSUE THREAD

**Issue by anthonycluse** [Unitech/keymetrics.io#52]
`pm2 list` doesn't work anymore... It was working before `pm2 interact`...

    anthoc@anthonycluseserver:~$ pm2 list

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: connect EACCES
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    anthoc@anthonycluseserver:~$ pm2 interact delete

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: connect EACCES
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    anthoc@anthonycluseserver:~$

**Comment by Unitech** [comment]
It looks like you have permission issues.
You must run `npm install pm2 -g` and `pm2 interact` with the same user

Do a `chown -R user:user ~/.pm2` to fix this
