### ISSUE TITLE
Error when I try to add new users

### ISSUE THREAD

**Issue by Ruiagf** [Unitech/keymetrics.io#54]
I cannot create new users. I'm getting an error "User unknown" when I try to add a new user.

Behind the scenes, the javascript console has the following error:

POST https://cl5.keymetrics.io/api/bucket/55031153bf29bfd28803fb13/add_user 404 (Not Found)

Thanks in advance.

**Comment by jorge-d** [comment]
Hello,

For the moment you can only invite users that have created a keymetrics account. It's not possible to invite non-registered user, however we are working on it.

All you need is that the user creates an account and then use the email he signed-up with in the form.

Best regards,

**Comment by Ruiagf** [comment]
Hi Jorge,

Thanks for your explanation. 

Best regards!
