### ISSUE TITLE
Wrong memory usage status

### ISSUE THREAD

**Issue by zhubofei** [Unitech/keymetrics.io#55]
![screen shot 2015-03-19 at 11 31 39 am](https://cloud.githubusercontent.com/assets/770482/6733935/a4bf7faa-ce2b-11e4-868c-44ee01f1d697.png)
![screen shot 2015-03-19 at 11 35 31 am](https://cloud.githubusercontent.com/assets/770482/6734019/1e923fa2-ce2c-11e4-8abb-172232fbfe17.png)
The instance has 1GB memory. I got the second graph from AWS cloud watch.

**Comment by jorge-d** [comment]
Hi,

We are aware of this issue,
Please have a look at #24 as it's a duplicate,

Thank you,
