### ISSUE TITLE
How to enable the pull, rollback, and upgrade buttons

### ISSUE THREAD

**Issue by jossi** [Unitech/keymetrics.io#56]
![screen shot 2015-03-26 at 10 25 38 am](https://cloud.githubusercontent.com/assets/444941/6852539/7e15a844-d3a2-11e4-9a6f-a5b877ecc40b.png)
In my buckets, the  pull, rollback, and upgrade buttons are disabled. How to enable them?

**Comment by jshkurti** [comment]
It is because you have Local changes on your repository folder (as the red indicator shows).
We prefer to disable Rollback/Pull/Upgrade features in this case to avoid conflicts or erasing data.
As soon as you have commited or checkout, you will be able to use those buttons again :)

**Comment by jossi** [comment]
Got it. Thanks!

**Comment by jossi** [comment]
What is the behavior of "Rollback"? Does it rollback to previous tag?

**Comment by jshkurti** [comment]
It does rollback to previous commit, not previous tag.
But, it is an intresting idea, we will consider implementing it in the future.
Thanks for the feedback !

**Comment by jossi** [comment]
I tried to pull and to rollback in the bucket and got "Not authorized".

We can pull without entering password as we are using SSH keys

**Comment by jossi** [comment]
What would be nice is when rolling back, you get to choose either last commit, or a specific tag to rollback to.

**Comment by jshkurti** [comment]
You have to be admin on the bucket.
For now, only the bucket's owner can.
We are going to implement some user ACL soon.
The rollback by tag is scheduled as well :)

**Comment by jossi** [comment]
Ah, great! ACL is needed as I am admin, but I need my devops to be able to do these actions

**Comment by jossi** [comment]
I did a pull as admin, and after that it locked:

![screen shot 2015-03-26 at 11 16 26 am](https://cloud.githubusercontent.com/assets/444941/6853630/957773a8-d3a9-11e4-982c-2867a793325e.png)

**Comment by jshkurti** [comment]
Well, this feature is experimental and is going to be refactored soon.
Thank your for the feedback again. We are working on it :)

**Comment by jossi** [comment]
kk

**Comment by jshkurti** [comment]
Hi @jossi 
I worked a bit on this feature. ACL is still not implemented, nor is rollback by tag.
But, it should be a bit more verbose on what is happening behind the scenes and it should not block your process anymore.
```npm i -g pm2``` to get the latest PM2 release 0.12.10 ;)
Cheers

**Comment by jossi** [comment]
Thanks!
