### ISSUE TITLE
Upgrading Node

### ISSUE THREAD

**Issue by martindale** [Unitech/keymetrics.io#59]
What is the recommended course of action for upgrading a running pm2 server from node 0.10 to node 0.12 without incurring downtime?

**Comment by jshkurti** [comment]
In theory, just ```pm2 update``` would be ok but since this is a really old version I would recommend : ```pm2 dump ; pm2 kill ; pm2 resurrect```

**Comment by martindale** [comment]
Ha, 0.10 isn't that old – [0.12 was only released last month](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/) and [0.10 continues to receive maintenance updates](http://blog.nodejs.org/2015/03/23/node-v0-10-38-maintenance/).

I think the theory here would be to restart individual processes, upgrading them from 0.10 to 0.12 one-by-one, and finally at the end upgrade pm2 itself.  I'm not sure that `pm2 update` deals with this.

**Comment by jorge-d** [comment]
I think installing latest node using `nvm` or any other solution and then installing pm2 again for that version and running `pm2 update` should do the trick ?

**Comment by martindale** [comment]
Aha.  I think Unitech/PM2#1034 answers my question.  Thanks!

**Comment by escopecz** [comment]
I went through all advices on how to force the PM2 daemon to use the new node version, but can't make it work. I did not try to re-install PM2 just yet. Don't want that long downtime.

I switched node version with nvm. If I `pm2 start app.js` via SSH on the server it uses the correct node version. But if I `pm2 deploy prod` on my local then it will start the processes in the old node version and it breaks the app.

Please advise on how to re-link the PM2 daemon to the new node version.
