### ISSUE TITLE
Pulls not triggering git hooks

### ISSUE THREAD

**Issue by mikkotikkanen** [Unitech/keymetrics.io#60]
I have a git hook (`post-merge`) setup that triggers on every pull (which then runs npm install), however, when triggered from the UI, the hook doesn't trigger.

**Comment by jshkurti** [comment]
```Personally, I got this working, however, in the context of npm and all, "postupdate" field name would make more sense (would follow the npm naming scheme). (you could have the "post_update" working as well for now and just change the documentation first)```

So did you find what you were looking for ? :)

Actually we do not ```git pull```.
We ```git remote update```, then check if the latest commit in HEAD is the same as the latest commit in remote/branch (```git log origin/master --pretty=oneline -n 1```).
If not, we ```git reset --hard <latest commit id in remote/branch>```.
That's why your hook on ```pull``` doesn't trigger.
I'm considering replacing all this by a ```git pull``` though :)

**Comment by mikkotikkanen** [comment]
Oh, well, that explains it :D

I initially had the `post-merge` hook doing the npm installs but when I started playing more with the keymetrics, since that didn't work, I had to switch to the `post_update` stuff. Which I got working, kinda. Issue incoming on that...

**Comment by mikkotikkanen** [comment]
Yeah, I guess the main issue is that the label in the button reads "pull", so naturally you'd expect it to do pull :)

**Comment by chrisinajar** [comment]
@mikkotikkanen How did you get this working? post-update runs on the repository and not within the clients, so it doesn't run on a reset either.

**Comment by jshkurti** [comment]
@chrisinajar https://github.com/Unitech/PM2/blob/master/doc/PULL.md check the json declaration example.
