### ISSUE TITLE
post_update scripts timing out?

### ISSUE THREAD

**Issue by mikkotikkanen** [Unitech/keymetrics.io#61]
I'm toying around with having Raspberry Pi as local development box. The post_update scripts from ecosystem.json trigger just nicely but for some unknown reason, the npm install --production fails. Only reason I can think of would be that it's timing out. Is there something of the sorts in place? Didn't find any documentation for it.

```
npm install --production
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/stack-trace

`npm install --production` failed
```

**Comment by jshkurti** [comment]
Yup, it times out after 30secondes for each command.
Any chance ```npm install``` takes longer ?
I'm going to make this configurable :)

**Comment by mikkotikkanen** [comment]
Yeah, for sure it takes longer since RPi isn't the most powerful machine out there. It can run node.js just fine but it's just the installing takes a bit.

**Comment by jshkurti** [comment]
Here we go https://github.com/Unitech/PM2/commit/4b7b4d38ce92b2ff6c2bf831233a1d80636b4e04
```npm i -g git://github.com/Unitech/PM2#development```

```"exec_timeout"       : 30000``` in the .json :)
By default it's 60sec now.

**Comment by jshkurti** [comment]
Setting it to 0 means no timeout at all :)

**Comment by mikkotikkanen** [comment]
Nice :) Thanks!
