### ISSUE TITLE
Keymetrics with dokku on Digitalocean

### ISSUE THREAD

**Issue by kaytrance** [Unitech/keymetrics.io#64]
Hi!

Weird things happening. I have sucessfully deployed an web app at digitalocean with dokku. To lauch/relaunch pm2 automatically after each deploy I have added a "scripts" line to package.json

```
"scripts": {
    "preinstall": "npm install -g pm2 && pm2 interact secret_key_hidden 90xtldwaq4pabgq digitalocean"
  }
```

This ensures that before I launch my app `pm2 interact` is initiated. And it is, because after running this line I can see that in my keymetrics dashboard  *Server #1 - digitalocean* is online. Next to this is a window with a line saying that **No application has been launched**. 

But when I then lauch my web app by `pm2 start server.js --name "server app" --no-daemon` (last key is needed to ensure that the dokku's buildpack completes without errors) dashboard still shows me that no app is launched, despite the fact that it is launched (because I can go to a **IP:port/route** and actualy see that the app is launched and working).

First I thought that it may be the port problem, but Digitalocean seems to be having all ports opened, so that port 80 and 43554, that are needed for keymetrics are opened).

Can you advide what may be wrong?

**Comment by jshkurti** [comment]
Hi,

Which version of pm2 are you using ?

**Comment by kaytrance** [comment]
Hi Joni!

Thanks for reply but I have already solved the problem.
Love keymetrics!

Best regards
KT

2015-04-16 18:33 GMT+03:00 Joni Shkurti <notifications@github.com>:

**Comment by jshkurti** [comment]
Great !
Can you tell us how you managed to solve the problem please ?
It might help some other users stumbling on the same issue.

**Comment by kaytrance** [comment]
Hi, Joni


It’s pretty simple, let me explain.


You have to make sure that you have only one file launched from your procfile. 

If you’ll have it like this:


worker: pm2 interact xxx yyy

web: pm2 server.js


it will fail because worker line will be like launched somewhat unreachable for web line.


If you try to launch them both under one web: line in procfile separating them with && (as you would do in Linux, for ex.) it will also fail because you can write only one command in each worker/web line (unfortunate restriction).


So how to solve it? Pretty simple.


make a launch.sh file and make it executable by chmod +x launch.sh


in that file write



#!/bin/bash

pm2 interact private_key public_key &&

pm2 start server.js --no-daemon -e log.txt -o log.txt

   

   3. in procfile write web: launch.sh


That's it! This will ensure that both interaction and process are launched in the same “area of visibility” and --no-daemon will force dokku to think that the process is still running (otherwise dokku will cancel deploy in post-deploy checks stage), and deploying will succeed. 


Using this you can see that I use keymetrics on my typwrittr.com hosted on digitalocean running dokku and it works like a charm.


So, do I deserve a premium for this hint? 😉


Best regards


KT





Sent from Windows Mail





From: Joni Shkurti
Sent: ‎Monday‎, ‎April‎ ‎20‎, ‎2015 ‎17‎:‎29
To: Unitech/keymetrics.io
Cc: Vadim Mamontov





Great !
Can you tell us how you managed to solve the problem please ?
It might help some other users stumbling on the same issue.

**Comment by jshkurti** [comment]
Thanks !
