### ISSUE TITLE
Dashboard showing HTTP avg but no routes

### ISSUE THREAD

**Issue by noodny** [Unitech/keymetrics.io#67]
I've set up pmx to log my app data, and the dashboard shows me an average http latency, but when I inspect it in Slow Routes, there is no data there.

![image](https://cloud.githubusercontent.com/assets/5416572/7155499/78e6287c-e35f-11e4-94b5-3f9ec792ef8c.png)
![image](https://cloud.githubusercontent.com/assets/5416572/7155509/8529925e-e35f-11e4-93fe-e7397eb47ed1.png)

Here's my code:
**server module**
```
var pmx = require('pmx').init(),
Stack = require('node-stack');
new Stack();
[...]
```
and then in
**node-stack module**
```
var http = require('http');
[...]
```

Is this an expected behavior, or should I be able to preview all the route samples?

**Comment by jshkurti** [comment]
HTTP avg takes in account all routes whereas the Slow routes page only shows routes with response time higher than 200ms or response code higher or equal to 500.
Would you be interested in configuring those limits in the pmx initialization such as : 
```
pmx.init(
  http: true,
  http_latency: 5, // logs all routes with response time > 5ms
  http_code: 200, // logs all routes with response code > 200
);
```
?

**Comment by noodny** [comment]
Yeah, that would be a great feature.

**Comment by jshkurti** [comment]
It's done :)
https://github.com/keymetrics/pmx/commit/fa8c9de665ccbdbfa88cf32e455fba970bc35479
```npm install -g pm2``` to get the latest pmx (v0.3.7) ;)

**Comment by jorge-d** [comment]
:thumbsup:
