### ISSUE TITLE
Explain what 'loop delay' is

### ISSUE THREAD

**Issue by adri** [Unitech/keymetrics.io#68]
I'm trying to find out what exactly 'loop delay' means. My google foo didn't bring any useful results.

Does it mean, that a new request has to wait for this time before it gets handled?

**Comment by jshkurti** [comment]
http://2014.jsconf.eu/speakers/philip-roberts-what-the-heck-is-the-event-loop-anyway.html

**Comment by adri** [comment]
Thanks @jshkurti. What does the loop delay mean in the context of node? 
Frames per second = requests per second?

**Comment by askhogan** [comment]
Loop delay is an interval whereby they set a function that loops and count how many ms off from the timer they set it is.  It is not requests per second, it is the amount of milliseconds of delay time it took to execute the interval.... meaning the event loop was blocked for that period of time.

**Comment by adri** [comment]
Awesome thanks Patrick.

**Comment by clivend** [comment]
what are good values for it?

**Comment by monochromatique** [comment]
run empty node.js app and you'll see min possible value

**Comment by robertnick04** [comment]
Is there anyway to mimize this loop back time. I am using PM2 and whle testing i am seeing 100 sec delay for each request when the test is running with 100 users. is there any performance tuning possible?

**Comment by marksherman** [comment]
@robertnick04 100 seconds? Like, a minute and a half? Are you sure it's not ms or fractions of a ms? I'm running an unoptimized mess on a research project and it's still 0.97ms. 100 seconds is ENORMOUS.

**Comment by liquidrinu** [comment]
Nodejs is set up to work async and as such even the most trivial non-async function would block the event loop for exactly as long as it takes the function to return. If you have seconds worth of delay, see if there are no sync functions anywhere. Nodejs has for examples synchronized counterpart functions for many of the async ones (ie. file reading) which should never be used in even the most trivial networking based application; use their async parts with awaits, promises or at the least 'as is' with a callback. You can easily wrap a 'regular js' sync function within one of those to make it async.
