### ISSUE TITLE
https://cl6.keymetrics.io Where is the file path?

### ISSUE THREAD

**Issue by zerataul** [Unitech/keymetrics.io#71]
Hello,

Https://cl6.keymetrics.io seen before in the Linux file saved files

I want to change the url.

Where is the file path??

**Comment by jorge-d** [comment]
Hi,

You should not access keymetrics dashboard using `clX.keymetrics.io`, the correct url is [https://app.keymetrics.io](https://app.keymetrics.io)

**Comment by zerataul** [comment]
I saw url is stored in the file, clX.keymetrics.io

I can't remember, but I wish find the file.

There is function sendData in PushInteractor.js
My plan
change the url and send data is the others server

**Comment by jshkurti** [comment]
I think you are talking about `~/.pm2/agent.json5` file.
When you `pm2 interact X Y` this file is updated so it sends data to the right server.
You don't actually have to change it manually.

What is your issue exactly ?
