### ISSUE TITLE
server memory usage seems to be incorrect

### ISSUE THREAD

**Issue by theoephraim** [Unitech/keymetrics.io#72]
Im showing 966.5 MB / 2.0 GB memory usage on the "Server Signs" tab

but on the machine, running htop shows me
391MB / 2001MB being used

newrelic also reports numbers near what htop is showing me.

**Comment by jorge-d** [comment]
Hi,

This is related to #24,
We might remove it from this tab as well,

**Comment by RyanCopley** [comment]
I'm experiencing the same issue... pm2 shouldn't be including the buffer / cache in its listings since linux will clear that out when there is memory pressure

**Comment by jorge-d** [comment]
This information does not appear anymore, for now we just display the total memory available on the server. Cheers,

**Comment by RyanCopley** [comment]
That is a step in the wrong direction...

**Comment by theoephraim** [comment]
That's unfortunate. Please bring it back (correctly) asap. New relic has this info so im sure there must be a way to get it.

**Comment by jorge-d** [comment]
Hi, you misunderstood what I just said.

As Unitech stated in #24:

    A module system in pm2 will able to install a specific application dedicated to monitor your server with multiple custom metrics for measuring I/O, Disk usage, CPU/Memory (+ maybe other things like security updates) in realtime + 14 days value retention

Meanwhile, we prefer to disabled this to avoid confusing our user with incorrect displayed memory value. You still have access to the right amount of memory used by each app in the app-signs tab.

Cheers,

**Comment by RyanCopley** [comment]
Knowing the amount of used memory on the server is crucial-- an application may not be using up a ton of ram but if our app goes haywire because redis is storing too much data, key metrics becomes useless... 

I believe we understand what you said, but we believe that seeing total real usage is an exceptionally important metric and should be prioritized... It's a pretty basic feature of these types of software

Doing OS specific implementations is fine, even modularity, but it is a very important feature. I really really like key metrics so I really hope this is taken seriously

**Comment by jorge-d** [comment]
Sure, as I told you we already have this future feature in our stack and we'll try to ship it as fast as possible :)

**Comment by Mishit07** [comment]
Is this fixed yet ?

**Comment by Unitech** [comment]
To get precise metrics for your server, please install pm2-server-monit module: https://github.com/pm2-hive/pm2-server-monit

**Comment by Mishit07** [comment]
Installed pm2-server-monit module. It shows current free memory. But When we go to 'Monitoring' tab the histogram doesn't show the graph for total physical memory. It breaks down my runniing apps in PM2 - app.js, log-rotate, server-monit We need simple histogram for total physical memory usage over the period of time.

**Comment by Unitech** [comment]
On the dashboard page, just click on the metrics "Free memory" and you will get a graph:

![keymetrics app](https://cloud.githubusercontent.com/assets/757747/13071487/0d7f96a0-d494-11e5-8527-f4454061dd57.png)
