### ISSUE TITLE
UX/UI Problem: Bottom Right info button taking up whole page

### ISSUE THREAD

**Issue by lozinge** [Unitech/keymetrics.io#74]
This might just be a problem with those with smaller screens, but if I change "tab" (e.g slow routes &rarr; exceptions) with the _help/info_ tab open it expands to take up the whole page.

![bug1](https://cloud.githubusercontent.com/assets/4786533/7549899/de31f774-f642-11e4-92fb-c54137b315e5.PNG)

![bug2](https://cloud.githubusercontent.com/assets/4786533/7549900/e6301230-f642-11e4-88f6-b608c4582442.PNG)

**Comment by jorge-d** [comment]
Hi,
Thanks for reporting this, it should be fixed now :)
Cheers,

**Comment by lozinge** [comment]
Can confirm - Cheers!
