### ISSUE TITLE
Limit email alerts

### ISSUE THREAD

**Issue by btmdave** [Unitech/keymetrics.io#77]
Is there a way to limit email alerts that are sent for the same alert type within a period of time?

We had an exception due to `EADDRINUSE` and was resolved after a few minutes, but at least 100 emails were sent in with this exception.

**Comment by btmdave** [comment]
I've also turned off all of the alerting and deleted the interactor, but they're still coming in.

**Comment by jorge-d** [comment]
This is strange, you are only supposed to receive an email on the first occurrence of the exception... What is your username ?

**Comment by btmdave** [comment]
@jorge-d can I email you our info?

**Comment by jorge-d** [comment]
Yes: dimitri [at] keymetrics [dot] io

**Comment by jorge-d** [comment]
For everyone that face the same issue please don't delete the exceptions your account, disabled email alerts and send me an email at the address above with your email or your bucket id.
