### ISSUE TITLE
Latency route analysis settings for long polling

### ISSUE THREAD

**Issue by lgelfan** [Unitech/keymetrics.io#79]
Is it possible to change the threshold settings or turn off latency route analysis logging? I'm using PM2 to manage an app that does long polling for websocket fall-back so almost all those requests are going to be flagged as "slow" as the average is going to be minutes, not ms. 

And if not, is there any harm (overhead) by logging all these requests?

Thanks.

**Comment by jshkurti** [comment]
The overhead is quite small.

Here, have a look at this :  https://github.com/keymetrics/pmx#installation

So, you can turn off route logging completely this way (this code has to be the first thing you do in your application, before any other require()): 
```js
var pmx = require('pmx').init({
  http          : false, // default : true
  ignore_routes : [/socket\.io/, /notFound/] // Ignore http routes with this pattern (Default: [])
});
```
But as you can see, you can also ignore some routes.
By default only the requests which take longer than 200ms or have a response code higher than 500 are logged.
You can change that with `http_latency : 200` and `http_code : 500` fields still in the pmx.init().

**Comment by lgelfan** [comment]
Ok, thanks much, I'm just starting to dig around and also wasn't quite clear on how to use PMX with PM2.

**Comment by jshkurti** [comment]
Glad I could help.
You also have `network` and `ports` flags which are quite useful :)
https://github.com/keymetrics/pmx#tcp-network-usage-monitoring
It should look like this on the dashboard : 
![probe1](https://cloud.githubusercontent.com/assets/7647602/7684405/033b27e4-fd86-11e4-970a-3a4d9d9f831a.png)
