### ISSUE TITLE
Answer your payments email - I want to be a customer :)

### ISSUE THREAD

**Issue by askhogan** [Unitech/keymetrics.io#80]
I sent an email several days ago to become a customer of keymetrics.  I love this dashboard.  Way better than Nodetime or StrongLoop.  There is nothing out there that combines the clustering metrics with the other features.  I am at the limit of servers I can launch and this is delaying my deployment project!  

Please put patrick@callinize.com down for a paid account

**Comment by Jbois** [comment]
Thank you for your kind words! Our apologies for the late reply. We are implementing a brand new payment system that will take into account the needs of customers more precisely. In the meantime, I upgraded your account for free so you can use Keymetrics to its fullest. Enjoy!

**Comment by askhogan** [comment]
Awesome man! Thanks!

**Comment by jshkurti** [comment]
:+1: :)
