### ISSUE TITLE
I can't seem to add a new user 

### ISSUE THREAD

**Issue by stringbeans** [Unitech/keymetrics.io#82]
Repro:
1. Go to settings
2. Type email into add new user field
3. Click add user

Expected:
New user is invited to keymetrics

Actual:
An error at the bottom of the screen says "User unknown"

**Comment by stringbeans** [comment]
As a side note, I am a "free" user however there doesn't seem to be any description of a limit on number of users...

**Comment by jorge-d** [comment]
Closing in favor of #20, for now you can only add users who have already created an account
