### ISSUE TITLE
Text overflow in UI dashboard

### ISSUE THREAD

**Issue by jpxd** [Unitech/keymetrics.io#83]
Hi,
on my 13 inch Macbook on fullscreen I have the following overflow in the dashboard

![screenshot 2015-06-16 10 07 29](https://cloud.githubusercontent.com/assets/10384363/8178577/9444f5e0-140f-11e5-9d45-e8bb2408f8f6.png)

**Comment by Unitech** [comment]
Click on + / - in the main dashboard to scale widgets
