### ISSUE TITLE
Dashboard stucked on realtime synchronization

### ISSUE THREAD

**Issue by sjamartucheli** [Unitech/keymetrics.io#85]
Hi guys,

I had a bucket on keymetrics running well in the last few months, but since last week the dashboard is stucked on this realtime synchronization screen.

I tried to restart the processes and update pm2, but it didn't work.

**Comment by jorge-d** [comment]
Hi,

Can you provide me your bucket id (the one in the url)?
Thanks,

**Comment by sjamartucheli** [comment]
Sure.
It's 551204fc97c161af9bb76dbd

**Comment by jorge-d** [comment]
Indeed there is an issue with your account, not with the bucket itself (it works for me when I log into your account). Can you sign out and sign in again?

**Comment by jorge-d** [comment]
Nailed it ! Your username was created before we added a rule that required username to be 4 chars min. Which username would you like to use instead of "idf" ?

**Comment by sjamartucheli** [comment]
If possible, "idfsis" would be perfect.

Thanks a lot.

**Comment by jorge-d** [comment]
Done,

You shouldn't have any problem now, feel free to reopen otherwise !
Cheers,
