### ISSUE TITLE
How do I un-link a process?

### ISSUE THREAD

**Issue by mmick66** [Unitech/keymetrics.io#87]
I ran 'pm2 link' (worked fine) and now I am wondering how you "un-link" a process. I am not fully familiar with PM2 but whenever I run the 'pm2 list' I can see that it is still linked so I am wondering about what resources it might be occupying and what internal ports it is blocking to keep that connection with keymetrics running.

**Comment by jorge-d** [comment]
You can run `pm2 interact stop` to stop sending data or `pm2 interact delete` to remove all the metadata stored (keys etc.)

**Comment by mmick66** [comment]
Thank you so much! (is it on your documentation?)

**Comment by jorge-d** [comment]
You're welcome,

When you run `pm2 commands`:
```sh
link [options] [secret_key|command] [public_key] [machine_name]      linking action to keymetrics.io - command can be stop|info|delete|restart
```

Each command is pretty self-explanatory I guess, but if you want to improve the doc feel free to do it :)

**Comment by adamreisnz** [comment]
`pm2 interact stop` command not found.
It appears it's now `pm2 unlink`

**Comment by igronus** [comment]
Don't forget to logout with `pm2 plus logout` if you aren't planning to have any processes there.
