### ISSUE TITLE
Wrong Node version reported

### ISSUE THREAD

**Issue by mzgol** [Unitech/keymetrics.io#88]
A few days ago I've switched from io.js 3.3.0 to Node.js 4.0.0 on my server; I've removed io.js completely, including its repo (I've been using https://github.com/nodesource/distributions/tree/master/deb for io.js, I use the same repo for Node.js 4 now). I've updated my server JavaScript code to a version that wouldn't be understood by io.js 3.3.0 so I know it's running on Node 4. However, https://app.keymetrics.io still shows the used Node version as io.js 3.3.0.

I've been restarting the app, both from the command line and the site UI but nothing changed.

**Comment by alavit-d** [comment]
It is likely that the pm2 daemon is the one running on io.js 3.3.0. Try `pm2 update` in command line and refresh the dashboard.

**Comment by mzgol** [comment]
Ah, thanks, I forgot about that. Note that now it shows "io.js 4.0.0" which is incorrect - there is no such version. :)

**Comment by alavit-d** [comment]
Waiting for PR https://github.com/Unitech/PM2/pull/1606

**Comment by mzgol** [comment]
Ok, thanks! I'm closing this one then.

**Comment by Unitech** [comment]
fixed

**Comment by knoxcard** [comment]
`pm2 update` did the trick! This should automatically run on` pm2 reload all`?
